### PR TITLE
`Simplify` now generates `Polygon` rings with at least four coordiantes

### LINKED ISSUE #142: Using Simplification algorithm on a polygon can result in an invalid polygon
https://github.com/georust/rust-geo/pull/135#issuecomment-320788702

Maybe the algorithm should sometimes return an `Option<T>` since it can sometimes fail.

### PR DESCRIPTION
**Pull request by frewsxcv**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Prior to this pull request, running `Simplify` on `Polygon` could generate rings with two coordinates, which would make it no longer a valid ring. This pull request updates `Simplify` to ensure resulting `Polygon` rings always have at least four coordinates.

Fixes #142

### CODE REVIEW

File: geo/src/algorithm/simplify.rs [hunk 1]
```diff
@@ -87,15 +98,34 @@ where
...
+    // The farthest index was less than or equal to epsilon, so we will retain only the first
+    // and last indices, resulting in the indices inbetween getting culled.
+
+    // Update `simplified_len` to reflect the new number of indices by subtracting the number
+    // of indices we're culling.
+    *simplified_len -= rdp_indices.len() - 2;
+
+    // If `simplified_len` is now lower than the minimum number of indices needed, then don't
+    // perform the culling and return the original input.
+    if *simplified_len <= INITIAL_MIN {
```
Comment (michaelkirk) [inline geo/src/algorithm/simplify.rs:123]: Can you imagine a situation where this returns a line much larger than INITIAL_MIN?

I'm not very familiar with this algorithm, but it seems like given a pathological 1000 coord polygon could be simplified in 1 step to 2 points, and then because that's below INITIAL_MIN, we'll instead return the original 1000 coord polygon. But I think I'd expect to get a 4-pt polygon in that case.

Or maybe that's not possible and I am misunderstanding.

Comment (frewsxcv) [reply geo/src/algorithm/simplify.rs:123]: Agreed we would ideally return a 4 coordinate polygon in that case, but I'm not sure how to modify this algorithm to make that happen, and which is maybe worthy of a separate issue. Unless you know a good solution for this case

Comment (frewsxcv) [reply geo/src/algorithm/simplify.rs:123]: @michaelkirk How do you feel about opening up a follow-up issue for optimizing in that scenario?

Comment (michaelkirk) [reply geo/src/algorithm/simplify.rs:123]: I actually don't feel that strongly about it, it's just what occurred to me. I'm happy to see it merged if you think it's an improvement.

**Comment by michaelkirk** [comment]
bors d=frewsxcv

**Comment by frewsxcv** [comment]
bors r=michaelkirk
